### ISSUE TITLE
[Training Error]: FineTunedModelDogfoodersEMU

### ISSUE THREAD

**Issue by monil-patel** [github-early-access/copilot-custom-models-beta#14] opened 2024-10-22 15:26 UTC
### Pipeline ID

48c77481-4689-4f37-8678-12ff80fe567d

we hit back to back failures this time around, figured someone may want to take a look

**Comment by Chaseshak** [comment] 2024-10-22 15:28
Hi @monil-patel! Thanks for the report. We've already identified the cause and are rolling out a fix shortly. I'll let you know when we've released the fix and you can retrain. Thanks!

**Comment by Chaseshak** [comment] 2024-10-22 15:44
@monil-patel We've shipped a fix for this, can you please try submitting another retrain?

**Comment by justincampbell** [comment] 2024-10-28 14:01
This looks to be fixed, let us know if you have any further issues or questions!

**Closed as completed by justincampbell** 2024-10-28 14:01 UTC
Labels: training-error
